
services:
  mongodb:
    image: mongo:7.0.5
    container_name: ecommerce_mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product
    volumes:
      - mongo:/data

  mysql:
    image: mysql:8.3.0
    container_name: ecommerce_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mongo:
  mysql: