spring:
  application:
    name: product-service
  mongodb:
    username: root
    password: password
    host: localhost
    port: 27017
    database: product
    authentication-database: admin

server:
  port: 4000
