spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:4000
              predicates:
                - Path=/api/product/**

            - id: order-service
              uri: http://localhost:4001
              predicates:
                - Path=/api/order/**

            - id: inventory-service
              uri: http://localhost:4002
              predicates:
                - Path=/api/inventory/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http:localhost:8081/realms/spring-microservice-realm
server:
  port: 5001
