---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  LOKI_URL: "http://loki.default.svc.cluster.local:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.default.svc.cluster.local:9411"
  PRODUCT_SERVICE_URL: "http://product-service.default.svc.cluster.local:4000"
  ORDER_SERVICE_URL: "http://order-service.default.svc.cluster.local:4001"
  INVENTORY_SERVICE_URL: "http://inventory-service.default.svc.cluster.local:4002"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "broker.default.svc.cluster.local:29092"